Failure # 1 (occurred at 2024-08-15_18-43-41)
[36mray::IMPALA.train()[39m (pid=184949, ip=192.168.1.54, actor_id=7d0f42edc28e6e2c89b7d11401000000, repr=IMPALA)
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 328, in train
    result = self.step()
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 962, in step
    train_results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 3492, in _run_one_training_iteration
    training_step_results = self.training_step()
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 657, in training_step
    return self._training_step_old_api_stack()
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 1034, in _training_step_old_api_stack
    self._get_samples_from_workers_old_and_hybrid_api_stack(
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/algorithms/impala/impala.py", line 1117, in _get_samples_from_workers_old_and_hybrid_api_stack
    ] = self.env_runner_group.fetch_ready_async_reqs(
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 1055, in fetch_ready_async_reqs
    _handle_remote_call_result_errors(
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 1264, in _handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(TypeError): [36mray::RolloutWorker.apply()[39m (pid=185053, ip=192.168.1.54, actor_id=da3bf93072f7d85b06bbb61a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7a82e4ed27a0>)
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/trand/miniconda3/envs/qsimpy/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
TypeError: cannot pickle 'generator' object
